### ISSUE TITLE
Help with agent socket messaging

### ISSUE THREAD

**Issue by dkebler** [dlech/SshAgentLib#24]
Been using keeagent for awhile and I really like the keeagent manager and would like to write my own stand alone GUI ssh agent manager since I can't find any project at github.

So, what I can't seem to find is documentation on the message format and content/commands that can be read and written to the agent socket (openSSH agent).  Can you point me to some and/or the file in this repo that uses them.  Should be pretty simple set (list keys, add a keys, delete a key, lock keys, unlock keys).  I suppose the might be the same as what `ssh-add` uses (I assume ssh-add uses the socket).

I mean the messages that are written and read here https://github.com/dlech/SshAgentLib/blob/990f8b695f8d733b66e267d95ca9e1552041cb12/SshAgentLib/UnixClient.cs 

Thx! for all your Kee related good works.

**Comment by dlech** [comment]
The protocol is described in https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.agent.

In this repo, it is implemented in `SshAgentLib/Agent.cs` and `SshAgentLib/AgentClient.cs`.

**Comment by dkebler** [comment]
Thanks for info, closing
