### ISSUE TITLE
SSH Agent mode not work in linux

### ISSUE THREAD

**Issue by Aetf** [dlech/SshAgentLib#4]
Environment variables `SSH_AUTH_SOCK` and `SSH_AGENT_PID` must be exported to entire session, otherwise other programs using ssh won't pick KeeAgent as its ssh-agent.

For other ssh-agent implementations, this work is usually done in a rc file or some kind of init script for the session where the program runs and returns something as a script to be eval. I can't find a way to archive the same thing as KeeAgent is a plugin but not a standalone program.

PS: I managed to rebuild these two variables from the specific path `/tmp/ssh-agent-lib-sock/` and here is the script I'm using
```
# Fix KeeAgent enviroment variable
set _ssh_socket_dir '/tmp/ssh-agent-lib-sock'
set _ssh_socket (ls --indicator-style=none "$_ssh_socket_dir")
if test -S "$_ssh_socket_dir/$_ssh_socket";
	setenv SSH_AGENT_PID (echo "$_ssh_socket" | sed 's/agent\.//g')
	setenv SSH_AUTH_SOCK "$_ssh_socket_dir/$_ssh_socket"
end
```
This is fish shell script so the syntax may be different but it's easy to adopt to bash, sh, etc.

**Comment by dlech** [comment]
Can this be closed? Agent mode on Linux was introduced in beta v0.7.7 and there is an open issue for notifications at dlech/KeeAgent#141.
